algoritmo "Primeiro"
var
 msg: caractere
 jd: caractere
 nome: caractere
 N1, N2, M: real
inicio
msg <- "Olá,mundo!"
jd <- "[legal isso aí kkk]"
escreva ("Digite o seu nome aqui ->:")
leia(nome)

escreva("Escreva um Número: ")
Leia(N1)
escreva("Escreva o seu segundo número: ")
leia(N2)

M <- (N1 + N2) /2
escreva("Muito prazer ", nome)
escreval("A media dos seus números", N1, " e", N2, " será igual a: ",M)
fimalgoritmo